import type { EditorThemeClasses } from 'lexical';
import './index.less';

const theme: EditorThemeClasses = {
  characterLimit: 'li-editor__characterLimit',
  code: 'li-editor__code',
  codeHighlight: {
    atrule: 'li-editor__tokenAttr',
    attr: 'li-editor__tokenAttr',
    boolean: 'li-editor__tokenProperty',
    builtin: 'li-editor__tokenSelector',
    cdata: 'li-editor__tokenComment',
    char: 'li-editor__tokenSelector',
    class: 'li-editor__tokenFunction',
    'class-name': 'li-editor__tokenFunction',
    comment: 'li-editor__tokenComment',
    constant: 'li-editor__tokenProperty',
    deleted: 'li-editor__tokenProperty',
    doctype: 'li-editor__tokenComment',
    entity: 'li-editor__tokenOperator',
    function: 'li-editor__tokenFunction',
    important: 'li-editor__tokenVariable',
    inserted: 'li-editor__tokenSelector',
    keyword: 'li-editor__tokenAttr',
    namespace: 'li-editor__tokenVariable',
    number: 'li-editor__tokenProperty',
    operator: 'li-editor__tokenOperator',
    prolog: 'li-editor__tokenComment',
    property: 'li-editor__tokenProperty',
    punctuation: 'li-editor__tokenPunctuation',
    regex: 'li-editor__tokenVariable',
    selector: 'li-editor__tokenSelector',
    string: 'li-editor__tokenSelector',
    symbol: 'li-editor__tokenProperty',
    tag: 'li-editor__tokenProperty',
    url: 'li-editor__tokenOperator',
    variable: 'li-editor__tokenVariable',
  },
  embedBlock: {
    base: 'li-editor__embedBlock',
    focus: 'li-editor__embedBlockFocus',
  },
  hashtag: 'li-editor__hashtag',
  heading: {
    h1: 'li-editor__h1',
    h2: 'li-editor__h2',
    h3: 'li-editor__h3',
    h4: 'li-editor__h4',
    h5: 'li-editor__h5',
    h6: 'li-editor__h6',
  },
  image: 'li-editor__image',
  link: 'li-editor__link',
  list: {
    listitem: 'li-editor__listItem',
    listitemChecked: 'li-editor__listItemChecked',
    listitemUnchecked: 'li-editor__listItemUnchecked',
    nested: {
      listitem: 'li-editor__nestedListItem',
    },
    olDepth: [
      'li-editor__ol1',
      'li-editor__ol2',
      'li-editor__ol3',
      'li-editor__ol4',
      'li-editor__ol5',
    ],
    ul: 'li-editor__ul',
  },
  ltr: 'li-editor__ltr',
  mark: 'li-editor__mark',
  markOverlap: 'li-editor__markOverlap',
  paragraph: 'li-editor__paragraph',
  quote: 'li-editor__quote',
  rtl: 'li-editor__rtl',
  table: 'li-editor__table',
  tableCell: 'li-editor__tableCell',
  tableCellHeader: 'li-editor__tableCellHeader',
  text: {
    bold: 'li-editor__textBold',
    code: 'li-editor__textCode',
    italic: 'li-editor__textItalic',
    strikethrough: 'li-editor__textStrikethrough',
    subscript: 'li-editor__textSubscript',
    superscript: 'li-editor__textSuperscript',
    underline: 'li-editor__textUnderline',
    underlineStrikethrough: 'li-editor__textUnderlineStrikethrough',
  },
};

export default theme;
