import type { EditorThemeClasses } from 'lexical'
import './text.css'

const theme: EditorThemeClasses = {
  characterLimit: 'li-editor-character-limit',
  code: 'li-editor-code',
  codeHighlight: {
    'atrule': 'li-editor-token-attr',
    'attr': 'li-editor-token-attr',
    'boolean': 'li-editor-token-property',
    'builtin': 'li-editor-token-selector',
    'cdata': 'li-editor-token-comment',
    'char': 'li-editor-token-selector',
    'class': 'li-editor-token-function',
    'class-name': 'li-editor-token-function',
    'comment': 'li-editor-token-comment',
    'constant': 'li-editor-token-property',
    'deleted': 'li-editor-token-property',
    'doctype': 'li-editor-token-comment',
    'entity': 'li-editor-token-operator',
    'function': 'li-editor-token-function',
    'important': 'li-editor-token-variable',
    'inserted': 'li-editor-token-selector',
    'keyword': 'li-editor-token-attr',
    'namespace': 'li-editor-token-variable',
    'number': 'li-editor-token-property',
    'operator': 'li-editor-token-operator',
    'prolog': 'li-editor-token-comment',
    'property': 'li-editor-token-property',
    'punctuation': 'li-editor-token-punctuation',
    'regex': 'li-editor-token-variable',
    'selector': 'li-editor-token-selector',
    'string': 'li-editor-token-selector',
    'symbol': 'li-editor-token-property',
    'tag': 'li-editor-token-property',
    'url': 'li-editor-token-operator',
    'variable': 'li-editor-token-variable',
  },
  embedBlock: {
    base: 'li-editor-embed-block',
    focus: 'li-editor-embed-block-focus',
  },
  hashtag: 'li-editor-hashtag',
  heading: {
    h1: 'li-editor-h1',
    h2: 'li-editor-h2',
    h3: 'li-editor-h3',
    h4: 'li-editor-h4',
    h5: 'li-editor-h5',
    h6: 'li-editor-h6',
  },
  image: 'editor-image',
  link: 'li-editor-link',
  list: {
    listitem: 'li-editor-listitem',
    listitemChecked: 'li-editor-listitem-checked',
    listitemUnchecked: 'li-editor-listitem-unchecked',
    nested: {
      listitem: 'li-editor-nested-listitem',
    },
    olDepth: [
      'li-editor-ol1',
      'li-editor-ol2',
      'li-editor-ol3',
      'li-editor-ol4',
      'li-editor-ol5',
    ],
    ul: 'li-editor-ul',
  },
  ltr: 'li-editor-ltr',
  mark: 'li-editor-mark',
  markOverlap: 'li-editor-markoverlap',
  paragraph: 'li-editor-paragraph',
  quote: 'li-editor-quote',
  rtl: 'li-editor-rtl',
  table: 'li-editor-table',
  tableAddColumns: 'li-editor-table-addcolumns',
  tableAddRows: 'li-editor-table-addrows',
  tableCell: 'li-editor-table-cell',
  tableCellActionButton: 'li-editor-table-cell-actionbutton',
  tableCellActionButtonContainer:
    'li-editor-table-cell-actionbutton-container',
  tableCellEditing: 'li-editor-table-cell-editing',
  tableCellHeader: 'li-editor-table-cell-header',
  tableCellPrimarySelected: 'li-editor-table-cell-primaryselected',
  tableCellResizer: 'li-editor-table-cell-resizer',
  tableCellSelected: 'li-editor-table-cell-selected',
  tableCellSortedIndicator: 'li-editor-table-cell-sortedindicator',
  tableResizeRuler: 'li-editor-table-cell-resizeruler',
  tableSelected: 'li-editor-table-selected',
  text: {
    bold: 'li-editor-text-bold',
    code: 'li-editor-text-code',
    italic: 'li-editor-text-italic',
    strikethrough: 'li-editor-text-strikethrough',
    subscript: 'li-editor-text-subscript',
    superscript: 'li-editor-text-superscript',
    underline: 'li-editor-text-underline',
    underlineStrikethrough: 'li-editor-text-underline-strikethrough',
  },
}

export default theme
